using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Pokemon.Models {
    public static class AttackTable {

        public static Dictionary<string, List<string>> movesDictionary = new Dictionary<string, List<string>>()
        {
            {"Abime", new List<string>{"--", "None", "Normal", "10", "Met K.O. l'adversaire d'un coup, mais a peu de chances de toucher."}},
            {"Acidarmure", new List<string>{"--", "DefUp", "Poison", "20", "Augmente la Défense du lanceur."}},
            {"Acide", new List<string>{"40", "DefSpeDown", "Poison", "30", "Inflige des dégâts. Baisse la Défense Spéciale de l'adversaire."}},
            {"Affutage", new List<string>{"--", "AtkUp", "Normal", "30", "Augmente l'Attaque du lanceur."}},
            {"Amnesie", new List<string>{"--", "DefSpeUp", "Psychic", "20", "Augmente la Défense Spéciale du lanceur."}},
            {"Armure", new List<string>{"--", "DefUp", "Normal", "30", "Augmente la Défense du lanceur."}},
            {"Balayage", new List<string>{"25", "None", "Fighting", "20", "Inflige des dégâts. Toujours touche l'adversaire."}},
            {"BecVrille", new List<string>{"80", "Confusion", "Normal", "20", "Inflige des dégâts. Peut rendre confus l'adversaire."}},
            {"Belier", new List<string>{"90", "None", "Normal", "20", "Inflige des dégâts. Blesse aussi l'utilisateur."}},
            {"Berceuse", new List<string>{"--", "Asleep", "Normal", "15", "Endort l'adversaire."}},
            {"Blizzard", new List<string>{"110", "Frozen", "Ice", "5", "Inflige des dégâts. Peut geler l'adversaire."}},
            {"BombeOeuf", new List<string>{"100", "None", "Normal", "10", "Inflige des dégâts."}},
            {"Bouclier", new List<string>{"--", "DefUp", "Normal", "30", "Augmente la Défense du lanceur."}},
            {"BoulArmure", new List<string>{"--", "DefUp", "Bug", "20", "Augmente la Défense du lanceur."}},
            {"Brouillard", new List<string>{"--", "None", "Ice", "20", "Réduit la Précision de l'adversaire."}},
            {"Brume", new List<string>{"--", "None", "Ice", "30", "Supprime les changements de stats de tous les Pokémon en combat."}},
            {"BueeNoire", new List<string>{"--", "None", "Ghost", "20", "Protège de toutes les attaques sauf celles qui sont directes."}},
            {"BullesdO", new List<string>{"40", "SpeedDown", "Water", "30", "Inflige des dégâts. Baisse la Vitesse de l'adversaire."}},
            {"CageEclair", new List<string>{"--", "None", "Electric", "20", "Empêche l'adversaire de fuir ou d'être remplacé."}},
            {"Cascade", new List<string>{"80", "None", "Water", "15", "Inflige des dégâts."}},
            {"Charge", new List<string>{"40", "None", "Normal", "35", "Inflige des dégâts."}},
            {"ChocMental", new List<string>{"50", "None", "Psychic", "25", "Inflige des dégâts."}},
            {"Claquoir", new List<string>{"85", "None", "Water", "10", "Inflige des dégâts."}},
            {"Clonage", new List<string>{"--", "None", "Normal", "10", "Crée une copie du lanceur pour augmenter son Esquive."}},
            {"ComboGriffe", new List<string>{"18", "None", "Normal", "15", "Inflige des dégâts à 2-5 reprises."}},
            {"Constriction", new List<string>{"10", "SpeedDown", "Normal", "35", "Inflige des dégâts. Baisse la Vitesse de l'adversaire."}},
            {"Conversion", new List<string>{"--", "None", "Normal", "30", "Modifie le type du lanceur pour correspondre à sa première attaque."}},
            {"Copie", new List<string>{"--", "None", "Normal", "20", "Copie la dernière attaque utilisée par l'adversaire."}},
            {"CoudKrane", new List<string>{"80", "None", "Steel", "15", "Inflige des dégâts."}},
            {"CoupDBoule", new List<string>{"70", "None", "Normal", "15", "Inflige des dégâts."}},
            {"Coupe", new List<string>{"50", "None", "Normal", "30", "Inflige des dégâts."}},
            {"CoupeVent", new List<string>{"80", "None", "Flying", "10", "Inflige des dégâts."}},
            {"CrocDeMort", new List<string>{"80", "None", "Dark", "15", "Inflige des dégâts."}},
            {"CrocFatal", new List<string>{"80", "None", "Dark", "15", "Inflige des dégâts."}},
            {"Croissance", new List<string>{"--", "AtkSpeUp", "Normal", "40", "Augmente l'Attaque Spéciale du lanceur."}},
            {"CruAiles", new List<string>{"60", "None", "Flying", "20", "Inflige des dégâts."}},
            {"Cyclone", new List<string>{"--", "None", "Flying", "20", "Fait fuir l'adversaire ou l'empêche d'utiliser une attaque prioritaire."}},
            {"Damocles", new List<string>{"120", "None", "Normal", "10", "Inflige des dégâts. Blesse aussi l'utilisateur."}},
            {"DanseFlammes", new List<string>{"--", "Burn", "Fire", "15", "Brûle l'adversaire."}},
            {"DanseFleurs", new List<string>{"--", "AtkSpeUp", "Grass", "10", "Augmente l'Attaque Spéciale du lanceur."}},
            {"DanseLames", new List<string>{"--", "AtkUp", "Normal", "20", "Augmente l'Attaque du lanceur."}},
            {"DardNuee", new List<string>{"14", "None", "Bug", "20", "Inflige des dégâts à 2-5 reprises."}},
            {"DardVenin", new List<string>{"15", "Poisonned", "Bug", "35", "Inflige des dégâts. Empoisonne l'adversaire."}},
            {"Deflagration", new List<string>{"110", "Burn", "Fire", "5", "Inflige des dégâts. Brûle l'adversaire."}},
            {"Destruction", new List<string>{"200", "None", "Normal", "5", "Inflige des dégâts. Blesse aussi l'utilisateur."}},
            {"Detritus", new List<string>{"60", "None", "Poison", "20", "Inflige des dégâts."}},
            {"Devoreve", new List<string>{"100", "None", "Psychic", "15", "Inflige des dégâts. Restaure les PV du lanceur à hauteur de la moitié des dégâts infligés."}},
            {"DoubleDard", new List<string>{"25", "None", "Bug", "20", "Inflige des dégâts à 2-5 reprises."}},
            {"DoublePied", new List<string>{"60", "None", "Fighting", "30", "Inflige des dégâts."}},
            {"DracoRage", new List<string>{"--", "None", "Dragon", "10", "Inflige des dégâts égaux à la moitié des PV max de l'adversaire."}},
            {"ECoque", new List<string>{"--", "DefUp", "Bug", "10", "Augmente la Défense du lanceur."}},
            {"Eboulement", new List<string>{"75", "None", "Rock", "10", "Inflige des dégâts. Peut faire tomber des rochers sur l'adversaire hors-combat."}},
            {"Eclair", new List<string>{"40", "Paralysed", "Electric", "30", "Inflige des dégâts. Peut paralyser l'adversaire."}},
            {"EcrasFace", new List<string>{"40", "None", "Normal", "35", "Inflige des dégâts."}},
            {"Ecrasement", new List<string>{"65", "None", "Normal", "20", "Inflige des dégâts."}},
            {"Ecume", new List<string>{"40", "None", "Water", "30", "Inflige des dégâts."}},
            {"EmpalKorne", new List<string>{"100", "None", "Normal", "10", "Inflige des dégâts."}},
            {"Entrave", new List<string>{"--", "None", "Normal", "20", "Empêche l'adversaire d'utiliser une attaque déjà utilisée."}},
            {"Etreinte", new List<string>{"15", "None", "Normal", "20", "Inflige des dégâts. Peut empêcher l'adversaire d'attaquer pendant quelques tours."}},
            {"Explosion", new List<string>{"250", "None", "Normal", "5", "Inflige des dégâts. Blesse aussi l'utilisateur."}},
            {"FatalFoudre", new List<string>{"110", "Paralysed", "Electric", "10", "Inflige des dégâts. Peut paralyser l'adversaire."}},
            {"Flammeche", new List<string>{"40", "Burn", "Fire", "25", "Inflige des dégâts. Brûle l'adversaire."}},
            {"Flash", new List<string>{"--", "AccDown", "Normal", "20", "Réduit la Précision de l'adversaire."}},
            {"Force", new List<string>{"80", "None", "Normal", "15", "Inflige des dégâts."}},
            {"ForcePoing", new List<string>{"150", "None", "Fighting", "5", "Inflige des dégâts."}},
            {"FouetLianes", new List<string>{"45", "None", "Grass", "25", "Inflige des dégâts."}},
            {"FrappeAtlas", new List<string>{"40", "None", "Fighting", "20", "Inflige des dégâts."}},
            {"Frenesie", new List<string>{"20", "None", "Normal", "20", "Inflige des dégâts à 2-5 reprises."}},
            {"Furie", new List<string>{"15", "None", "Normal", "20", "Inflige des dégâts à 2-5 reprises."}},
            {"GazToxik", new List<string>{"--", "Poisonned", "Poison", "40", "Empoisonne l'adversaire."}},
            {"Griffe", new List<string>{"40", "None", "Normal", "35", "Inflige des dégâts."}},
            {"Grincement", new List<string>{"--", "DefDown", "Normal", "40", "Baisse la Défense de l'adversaire."}},
            {"Grobisou", new List<string>{"--", "Asleep", "Normal", "10", "Endort l'adversaire."}},
            {"GrozYeux", new List<string>{"--", "AccDown", "Normal", "30", "Baisse la Précision de l'adversaire."}},
            {"Guillotine", new List<string>{"--", "None", "Normal", "5", "Met K.O. l'adversaire d'un coup, mais a peu de chances de toucher."}},
            {"Hate", new List<string>{"--", "None", "Normal", "20", "Augmente la Vitesse du lanceur."}},
            {"Hurlement", new List<string>{"--", "None", "Normal", "20", "Force l'adversaire à être remplacé par un autre Pokémon."}},
            {"Hydrocanon", new List<string>{"110", "None", "Water", "5", "Inflige des dégâts."}},
            {"Hypnose", new List<string>{"--", "Asleep", "Psychic", "20", "Endort l'adversaire."}},
            {"Jackpot", new List<string>{"--", "None", "Normal", "5", "Inflige des dégâts. Plus de dégâts si l'utilisateur a moins de PV."}},
            {"JetDeSable", new List<string>{"--", "None", "Ground", "15", "Baisse la Précision de l'adversaire."}},
            {"JetPierres", new List<string>{"50", "None", "Rock", "10", "Inflige des dégâts."}},
            {"KoudKrone", new List<string>{"130", "None", "Ice", "5", "Inflige des dégâts."}},
            {"LanceFlammes", new List<string>{"90", "Burn", "Fire", "15", "Inflige des dégâts. Brûle l'adversaire."}},
            {"LanceSoleil", new List<string>{"120", "None", "Grass", "10", "Inflige des dégâts. Le lanceur doit recharger au tour suivant."}},
            {"LaserGlace", new List<string>{"90", "None", "Ice", "10", "Inflige des dégâts."}},
            {"Lechouille", new List<string>{"80", "Paralysed", "Ghost", "10", "Inflige des dégâts. Peut paralyser l'adversaire."}},
            {"Ligotage", new List<string>{"15", "None", "Normal", "20", "Inflige des dégâts. Peut empêcher l'adversaire d'attaquer pendant quelques tours."}},
            {"Lilliput", new List<string>{"--", "None", "Normal", "20", "Augmente l'Esquive du lanceur."}},
            {"Lutte", new List<string>{"50", "None", "Normal", "30", "Inflige des dégâts."}},
            {"Mania", new List<string>{"120", "None", "Grass", "10", "Inflige des dégâts. Le lanceur doit recharger au tour suivant."}},
            {"MassdOs", new List<string>{"65", "None", "Ground", "20", "Inflige des dégâts."}},
            {"MawashiGeri", new List<string>{"60", "None", "Fighting", "15", "Inflige des dégâts."}},
            {"MegaSangsue", new List<string>{"40", "None", "Grass", "15", "Inflige des dégâts. Restaure les PV du lanceur à hauteur de la moitié des dégâts infligés."}},
            {"Meteores", new List<string>{"60", "None", "Psychic", "20", "Inflige des dégâts."}},
            {"Metronome", new List<string>{"--", "None", "Normal", "10", "Utilise une attaque au hasard parmi toutes les attaques connues."}},
            {"MimiQueue", new List<string>{"--", "AccDown", "Normal", "30", "Baisse la Précision de l'adversaire."}},
            {"Mimique", new List<string>{"--", "None", "Normal", "10", "Copie la dernière attaque utilisée par l'adversaire."}},
            {"Morphing", new List<string>{"--", "None", "Normal", "10", "Modifie le type du lanceur pour correspondre à la première attaque de l'adversaire."}},
            {"Morsure", new List<string>{"60", "Flinch", "Dark", "25", "Inflige des dégâts. Peut faire flancher l'adversaire."}},
            {"MurLumiere", new List<string>{"--", "None", "Psychic", "30", "Réduit les dégâts des attaques spéciales pendant 5 tours."}},
            {"OmbreNocturne", new List<string>{"95", "None", "Ghost", "15", "Inflige des dégâts."}},
            {"OndeBoreale", new List<string>{"65", "None", "Ice", "20", "Inflige des dégâts."}},
            {"OndeFolie", new List<string>{"--", "Confused", "Psychic", "10", "Confuse l'adversaire."}},
            {"Osmerang", new List<string>{"50", "None", "Ground", "10", "Inflige des dégâts à 2 reprises."}},
            {"ParaSpore", new List<string>{"--", "Paralysed", "Grass", "30", "Paralyse l'adversaire."}},
            {"Patience", new List<string>{"--", "None", "Normal", "10", "Augmente la Puissance de l'attaque du lanceur à chaque fois qu'il subit des dégâts."}},
            {"Picanon", new List<string>{"120", "None", "Water", "5", "Inflige des dégâts. Le lanceur doit recharger au tour suivant."}},
            {"Picpic", new List<string>{"35", "None", "Flying", "35", "Inflige des dégâts."}},
            {"PiedSaute", new List<string>{"70", "None", "Fighting", "25", "Inflige des dégâts."}},
            {"PiedVoltige", new List<string>{"85", "None", "Flying", "20", "Inflige des dégâts."}},
            {"Pilonnage", new List<string>{"15", "None", "Normal", "20", "Inflige des dégâts à 2-5 reprises."}},
            {"PinceMasse", new List<string>{"90", "None", "Water", "10", "Inflige des dégâts."}},
            {"Pique", new List<string>{"140", "None", "Normal", "5", "Inflige des dégâts."}},
            {"PistoletAO", new List<string>{"40", "None", "Water", "25", "Inflige des dégâts."}},
            {"Plaquage", new List<string>{"85", "None", "Normal", "15", "Inflige des dégâts. Blesse aussi l'utilisateur."}},
            {"PoingComete", new List<string>{"100", "None", "Normal", "5", "Inflige des dégâts."}},
            {"PoingEclair", new List<string>{"75", "Paralysed", "Electric", "15", "Inflige des dégâts. Peut paralyser l'adversaire."}},
            {"PoingFeu", new List<string>{"75", "Burn", "Fire", "15", "Inflige des dégâts. Brûle l'adversaire."}},
            {"PoingGlace", new List<string>{"75", "None", "Ice", "15", "Inflige des dégâts."}},
            {"PoingKarate", new List<string>{"50", "None", "Fighting", "25", "Inflige des dégâts."}},
            {"PoudreDodo", new List<string>{"--", "Asleep", "Bug", "15", "Endort l'adversaire."}},
            {"PoudreToxik", new List<string>{"--", "Poisonned", "Bug", "20", "Empoisonne l'adversaire."}},
            {"Protection", new List<string>{"--", "None", "Normal", "20", "Empêche toutes les attaques de toucher le lanceur pendant un tour."}},
            {"Psyko", new List<string>{"90", "None", "Psychic", "10", "Inflige des dégâts."}},
            {"Puissance", new List<string>{"60", "None", "Normal", "20", "Inflige des dégâts."}},
            {"PureDPois", new List<string>{"--", "Poisonned", "Poison", "20", "Empoisonne l'adversaire."}},
            {"RafalePsy", new List<string>{"65", "None", "Psychic", "20", "Inflige des dégâts."}},
            {"Reflet", new List<string>{"--", "None", "Normal", "15", "Augmente l'Esquive du lanceur."}},
            {"RegardMedusant", new List<string>{"--", "Paralysed", "Normal", "30", "Peut paralyser l'adversaire."}},
            {"Repli", new List<string>{"--", "None", "Normal", "40", "Augmente la Défense du lanceur."}},
            {"Repos", new List<string>{"--", "Asleep", "Psychic", "10", "Le lanceur récupère tous ses PV et s'endort pendant 2 tours."}},
            {"Riposte", new List<string>{"--", "None", "Fighting", "20", "Inflige des dégâts. Si le lanceur est attaqué par une attaque physique, inflige le double des dégâts subis."}},
            {"Rugissement", new List<string>{"--", "None", "Normal", "40", "Baisse l'Attaque de l'adversaire."}},
            {"Sacrifice", new List<string>{"--", "None", "Normal", "25", "Blesse l'utilisateur d'un montant égal aux PV max de l'adversaire."}},
            {"Secretion", new List<string>{"--", "None", "Bug", "40", "Baisse la Vitesse de l'adversaire."}},
            {"Seisme", new List<string>{"100", "None", "Ground", "10", "Inflige des dégâts. Touche tous les Pokémon en combat sauf le lanceur."}},
            {"Soin", new List<string>{"--", "None", "Psychic", "10", "Restaure les PV du lanceur."}},
            {"SonicBoom", new List<string>{"--", "None", "Normal", "20", "Inflige toujours 20 points de dégâts."}},
            {"Souplesse", new List<string>{"80", "None", "Normal", "20", "Inflige des dégâts."}},
            {"Spore", new List<string>{"--", "Asleep", "Grass", "15", "Endort l'adversaire."}},
            {"Surf", new List<string>{"90", "None", "Water", "15", "Inflige des dégâts. Attaque tous les Pokémon en combat sauf le lanceur."}},
            {"Telekinesie", new List<string>{"--", "None", "Psychic", "15", "Permet d'attaquer les Pokémon de type Sol ou les Pokémon en vol."}},
            {"Teleport", new List<string>{"--", "None", "Psychic", "20", "Permet de s'échapper d'un combat sauvage."}},
            {"Tonnerre", new List<string>{"90", "Paralysed", "Electric", "15", "Inflige des dégâts. Peut paralyser l'adversaire."}},
            {"Torgnoles", new List<string>{"15", "None", "Normal", "10", "Inflige des dégâts à 2-5 reprises."}},
            {"Tornade", new List<string>{"110", "None", "Flying", "10", "Inflige des dégâts. Peut faire partir l'adversaire en vol."}},
            {"Toxik", new List<string>{"--", "Poisonned", "Poison", "10", "Empoisonne l'adversaire."}},
            {"TranchHerbe", new List<string>{"55", "None", "Grass", "25", "Inflige des dégâts."}},
            {"Tranche", new List<string>{"70", "None", "Normal", "20", "Inflige des dégâts."}},
            {"Trempette", new List<string>{"--", "None", "Water", "40", "Le lanceur est trempé. Ne fait rien si le terrain est un autre type que l'Eau."}},
            {"Triplattaque", new List<string>{"80", "None", "Normal", "10", "Inflige des dégâts. Peut brûler, paralyser ou geler l'adversaire."}},
            {"Tunnel", new List<string>{"80", "None", "Ground", "10", "Inflige des dégâts. Peut augmenter la Défense du lanceur."}},
            {"Ultimapoing", new List<string>{"80", "None", "Normal", "5", "Inflige des dégâts."}},
            {"Utlimawashi", new List<string>{"85", "None", "Fighting", "5", "Inflige des dégâts."}},
            {"UltraLaser", new List<string>{"150", "None", "Normal", "5", "Inflige des dégâts. Le lanceur doit recharger au tour suivant."}},
            {"UltraSon", new List<string>{"20", "None", "Normal", "20", "Inflige des dégâts. Peut empêcher l'adversaire d'attaquer pendant quelques tours."}},
            {"Uppercut", new List<string>{"70", "None", "Fighting", "20", "Inflige des dégâts."}},
            {"VaguePsy", new List<string>{"90", "None", "Psychic", "10", "Inflige des dégâts."}},
            {"Vampigraine", new List<string>{"--", "LeechSeed", "Grass", "10", "Plante des graines sur l'adversaire. Le lanceur récupère des PV à chaque tour."}},
            {"Vampirisme", new List<string>{"20", "None", "Normal", "15", "Inflige des dégâts. Le lanceur récupère des PV à hauteur de la moitié des dégâts infligés."}},
            {"VivaAttaque", new List<string>{"70", "None", "Normal", "20", "Inflige des dégâts."}},
            {"Vol", new List<string>{"90", "None", "Flying", "15", "Inflige des dégâts. Le lanceur s'envole et attaque au tour suivant."}},
            {"VoleVie", new List<string>{"20", "None", "Grass", "25", "Inflige des dégâts. Le lanceur récupère des PV à hauteur de la moitié des dégâts infligés."}},
            {"Yoga", new List<string>{"0", "None", "Psychic", "40", "Augmente l'Attaque Spéciale du lanceur."}},
        };
    }
}
