using Pokemon.Enums;

namespace Pokemon.Models {
    public static class PokemonTable {

        public static Pokemons GeneratePokemon( string name, int level ) {

            return name.ToLower() switch {
                "bulbizarre" => new Pokemons( "Bulbizarre", level, new Dictionary<string, int> { { "hp", 45 }, { "atk", 49 }, { "def", 49 }, { "atkspe", 65 }, { "defspe", 65 }, { "speed", 45 }, { "special", 65 } },
                                                        new List<Types> { Types.Grass, Types.Poison }, 0.7, 6.9 ),
                "herbizarre" => new Pokemons( "Herbizarre", level, new Dictionary<string, int> { { "hp", 60 }, { "atk", 62 }, { "def", 63 }, { "atkspe", 80 }, { "defspe", 80 }, { "speed", 60 }, { "special", 80 } },
                                                        new List<Types> { Types.Grass, Types.Poison }, 1.0, 13.0 ),
                "florizarre" => new Pokemons( "Florizarre", level, new Dictionary<string, int> { { "hp", 80 }, { "atk", 82 }, { "def", 83 }, { "atkspe", 100 }, { "defspe", 100 }, { "speed", 80 }, { "special", 100 } },
                                                        new List<Types> { Types.Grass, Types.Poison }, 2.0, 100.0 ),
                "salameche" => new Pokemons( "Salameche", level, new Dictionary<string, int> { { "hp", 39 }, { "atk", 52 }, { "def", 43 }, { "atkspe", 60 }, { "defspe", 50 }, { "speed", 65 }, { "special", 50 } },
                                                        new List<Types> { Types.Fire }, 0.6, 8.5 ),
                "reptincel" => new Pokemons( "Reptincel", level, new Dictionary<string, int> { { "hp", 58 }, { "atk", 64 }, { "def", 58 }, { "atkspe", 80 }, { "defspe", 65 }, { "speed", 80 }, { "special", 65 } },
                                                        new List<Types> { Types.Fire }, 1.1, 19.0 ),
                "dracaufeu" => new Pokemons( "Dracaufeu", level, new Dictionary<string, int> { { "hp", 78 }, { "atk", 84 }, { "def", 78 }, { "atkspe", 109 }, { "defspe", 85 }, { "speed", 100 }, { "special", 85 } },
                                                        new List<Types> { Types.Fire, Types.Flying }, 1.7, 90.5 ),
                "carapuce" => new Pokemons( "Carapuce", level, new Dictionary<string, int> { { "hp", 44 }, { "atk", 48 }, { "def", 65 }, { "atkspe", 50 }, { "defspe", 64 }, { "speed", 43 }, { "special", 50 } },
                                                        new List<Types> { Types.Water }, 0.5, 9.0 ),
                "carabaffe" => new Pokemons( "Carabaffe", level, new Dictionary<string, int> { { "hp", 59 }, { "atk", 63 }, { "def", 80 }, { "atkspe", 65 }, { "defspe", 80 }, { "speed", 58 }, { "special", 65 } },
                                                        new List<Types> { Types.Water }, 1.0, 22.5 ),
                "tortank" => new Pokemons( "Tortank", level, new Dictionary<string, int> { { "hp", 79 }, { "atk", 83 }, { "def", 100 }, { "atkspe", 85 }, { "defspe", 105 }, { "speed", 78 }, { "special", 85 } },
                                                        new List<Types> { Types.Water }, 1.6, 85.5 ),
                "chenipan" => new Pokemons( "Chenipan", level, new Dictionary<string, int> { { "hp", 45 }, { "atk", 30 }, { "def", 35 }, { "atkspe", 20 }, { "defspe", 20 }, { "speed", 45 }, { "special", 20 } },
                                                        new List<Types> { Types.Bug }, 0.3, 2.9 ),
                "chrysacier" => new Pokemons( "Chrysacier", level, new Dictionary<string, int> { { "hp", 50 }, { "atk", 20 }, { "def", 55 }, { "atkspe", 25 }, { "defspe", 25 }, { "speed", 30 }, { "special", 25 } },
                                                        new List<Types> { Types.Bug }, 0.7, 9.9 ),
                "papilusion" => new Pokemons( "Papilusion", level, new Dictionary<string, int> { { "hp", 60 }, { "atk", 45 }, { "def", 50 }, { "atkspe", 90 }, { "defspe", 80 }, { "speed", 70 }, { "special", 80 } },
                                                        new List<Types> { Types.Bug, Types.Flying }, 1.1, 32.0 ),
                "aspicot" => new Pokemons( "Aspicot", level, new Dictionary<string, int> { { "hp", 40 }, { "atk", 35 }, { "def", 30 }, { "atkspe", 20 }, { "defspe", 20 }, { "speed", 50 }, { "special", 20 } },
                                                        new List<Types> { Types.Bug, Types.Poison }, 0.3, 3.2 ),
                "coconfort" => new Pokemons( "Coconfort", level, new Dictionary<string, int> { { "hp", 45 }, { "atk", 25 }, { "def", 50 }, { "atkspe", 25 }, { "defspe", 25 }, { "speed", 35 }, { "special", 25 } },
                                                        new List<Types> { Types.Bug, Types.Poison }, 0.7, 10.0 ),
                "dardargnan" => new Pokemons( "Dardargnan", level, new Dictionary<string, int> { { "hp", 65 }, { "atk", 80 }, { "def", 40 }, { "atkspe", 45 }, { "defspe", 80 }, { "speed", 75 }, { "special", 45 } },
                                                        new List<Types> { Types.Bug, Types.Poison }, 1.5, 29.5 ),
                "roucool" => new Pokemons( "Roucool", level, new Dictionary<string, int> { { "hp", 40 }, { "atk", 45 }, { "def", 40 }, { "atkspe", 35 }, { "defspe", 35 }, { "speed", 56 }, { "special", 35 } },
                                                        new List<Types> { Types.Normal, Types.Flying }, 0.3, 1.8 ),
                "roucoups" => new Pokemons( "Roucoups", level, new Dictionary<string, int> { { "hp", 63 }, { "atk", 60 }, { "def", 55 }, { "atkspe", 50 }, { "defspe", 50 }, { "speed", 71 }, { "special", 50 } },
                                                        new List<Types> { Types.Normal, Types.Flying }, 1.1, 30.0 ),
                "roucarnage" => new Pokemons( "Roucarnage", level, new Dictionary<string, int> { { "hp", 83 }, { "atk", 80 }, { "def", 75 }, { "atkspe", 70 }, { "defspe", 70 }, { "speed", 101 }, { "special", 70 } },
                                                        new List<Types> { Types.Normal, Types.Flying }, 1.5, 39.5 ),
                "rattata" => new Pokemons( "Rattata", level, new Dictionary<string, int> { { "hp", 30 }, { "atk", 56 }, { "def", 35 }, { "atkspe", 25 }, { "defspe", 35 }, { "speed", 72 }, { "special", 25 } },
                                                        new List<Types> { Types.Normal }, 0.3, 3.5 ),
                "rattatac" => new Pokemons( "Rattatac", level, new Dictionary<string, int> { { "hp", 55 }, { "atk", 81 }, { "def", 60 }, { "atkspe", 50 }, { "defspe", 70 }, { "speed", 97 }, { "special", 50 } },
                                                        new List<Types> { Types.Normal }, 0.7, 18.5 ),
                "piafabec" => new Pokemons( "Piafabec", level, new Dictionary<string, int> { { "hp", 40 }, { "atk", 60 }, { "def", 30 }, { "atkspe", 31 }, { "defspe", 31 }, { "speed", 70 }, { "special", 31 } },
                                                        new List<Types> { Types.Normal, Types.Flying }, 0.3, 2.0 ),
                "rapasdepic" => new Pokemons( "Rapasdepic", level, new Dictionary<string, int> { { "hp", 65 }, { "atk", 90 }, { "def", 65 }, { "atkspe", 61 }, { "defspe", 61 }, { "speed", 100 }, { "special", 61 } },
                                                        new List<Types> { Types.Normal, Types.Flying }, 1.2, 38.0 ),
                "abo" => new Pokemons( "Abo", level, new Dictionary<string, int> { { "hp", 35 }, { "atk", 60 }, { "def", 44 }, { "atkspe", 40 }, { "defspe", 54 }, { "speed", 55 }, { "special", 40 } },
                                                        new List<Types> { Types.Poison }, 2.0, 6.9 ),
                "arbok" => new Pokemons( "Arbok", level, new Dictionary<string, int> { { "hp", 60 }, { "atk", 95 }, { "def", 69 }, { "atkspe", 65 }, { "defspe", 79 }, { "speed", 80 }, { "special", 65 } },
                                                        new List<Types> { Types.Poison }, 3.5, 65.0 ),
                "pikachu" => new Pokemons( "Pikachu", level, new Dictionary<string, int> { { "hp", 35 }, { "atk", 55 }, { "def", 40 }, { "atkspe", 50 }, { "defspe", 50 }, { "speed", 90 }, { "special", 50 } },
                                                        new List<Types> { Types.Electric }, 0.4, 6.0 ),
                "raichu" => new Pokemons( "Raichu", level, new Dictionary<string, int> { { "hp", 60 }, { "atk", 90 }, { "def", 55 }, { "atkspe", 90 }, { "defspe", 80 }, { "speed", 110 }, { "special", 90 } },
                                                        new List<Types> { Types.Electric }, 0.8, 30.0 ),
                "sabelette" => new Pokemons( "Sabelette", level, new Dictionary<string, int> { { "hp", 50 }, { "atk", 75 }, { "def", 85 }, { "atkspe", 20 }, { "defspe", 30 }, { "speed", 40 }, { "special", 20 } },
                                                        new List<Types> { Types.Ground }, 0.6, 12.0 ),
                "sablaireau" => new Pokemons( "Sablaireau", level, new Dictionary<string, int> { { "hp", 75 }, { "atk", 100 }, { "def", 110 }, { "atkspe", 45 }, { "defspe", 55 }, { "speed", 65 }, { "special", 45 } },
                                                        new List<Types> { Types.Ground }, 1.0, 29.5 ),
                "nidoranf" => new Pokemons( "nidoranf", level, new Dictionary<string, int> { { "hp", 55 }, { "atk", 47 }, { "def", 52 }, { "atkspe", 40 }, { "defspe", 40 }, { "speed", 41 }, { "special", 40 } },
                                                        new List<Types> { Types.Poison }, 0.4, 7.0 ),
                "nidorina" => new Pokemons( "Nidorina", level, new Dictionary<string, int> { { "hp", 70 }, { "atk", 62 }, { "def", 67 }, { "atkspe", 55 }, { "defspe", 55 }, { "speed", 56 }, { "special", 55 } },
                                                        new List<Types> { Types.Poison }, 0.8, 20.0 ),
                "nidoqueen" => new Pokemons( "Nidoqueen", level, new Dictionary<string, int> { { "hp", 90 }, { "atk", 92 }, { "def", 87 }, { "atkspe", 75 }, { "defspe", 85 }, { "speed", 76 }, { "special", 75 } },
                                                        new List<Types> { Types.Poison, Types.Ground }, 1.3, 60.0 ),
                "nidoranm" => new Pokemons( "nidoranm", level, new Dictionary<string, int> { { "hp", 46 }, { "atk", 57 }, { "def", 40 }, { "atkspe", 40 }, { "defspe", 40 }, { "speed", 50 }, { "special", 40 } },
                                                        new List<Types> { Types.Poison }, 0.5, 9.0 ),
                "nidorino" => new Pokemons( "Nidorino", level, new Dictionary<string, int> { { "hp", 61 }, { "atk", 72 }, { "def", 57 }, { "atkspe", 55 }, { "defspe", 55 }, { "speed", 65 }, { "special", 55 } },
                                                        new List<Types> { Types.Poison }, 0.9, 19.5 ),
                "nidoking" => new Pokemons( "Nidoking", level, new Dictionary<string, int> { { "hp", 81 }, { "atk", 102 }, { "def", 77 }, { "atkspe", 85 }, { "defspe", 75 }, { "speed", 85 }, { "special", 75 } },
                                                        new List<Types> { Types.Poison, Types.Ground }, 1.4, 62.0 ),
                "melofee" => new Pokemons( "Melofee", level, new Dictionary<string, int> { { "hp", 70 }, { "atk", 45 }, { "def", 48 }, { "atkspe", 60 }, { "defspe", 65 }, { "speed", 35 }, { "special", 60 } },
                                                        new List<Types> { Types.Normal }, 0.6, 7.5 ),
                "melodelfe" => new Pokemons( "Melodelfe", level, new Dictionary<string, int> { { "hp", 95 }, { "atk", 70 }, { "def", 73 }, { "atkspe", 85 }, { "defspe", 90 }, { "speed", 60 }, { "special", 85 } },
                                                        new List<Types> { Types.Normal }, 1.0, 40.0 ),
                "goupix" => new Pokemons( "Goupix", level, new Dictionary<string, int> { { "hp", 38 }, { "atk", 41 }, { "def", 40 }, { "atkspe", 50 }, { "defspe", 65 }, { "speed", 65 }, { "special", 50 } },
                                                        new List<Types> { Types.Fire }, 0.6, 9.9 ),
                "feunard" => new Pokemons( "Feunard", level, new Dictionary<string, int> { { "hp", 73 }, { "atk", 76 }, { "def", 75 }, { "atkspe", 81 }, { "defspe", 100 }, { "speed", 100 }, { "special", 81 } },
                                                        new List<Types> { Types.Fire }, 1.1, 19.9 ),
                "rondoudou" => new Pokemons( "Rondoudou", level, new Dictionary<string, int> { { "hp", 115 }, { "atk", 45 }, { "def", 20 }, { "atkspe", 45 }, { "defspe", 25 }, { "speed", 20 }, { "special", 45 } },
                                                        new List<Types> { Types.Normal, Types.Fairy }, 0.5, 5.5 ),
                "grodoudou" => new Pokemons( "Grodoudou", level, new Dictionary<string, int> { { "hp", 140 }, { "atk", 70 }, { "def", 45 }, { "atkspe", 85 }, { "defspe", 50 }, { "speed", 45 }, { "special", 90 } },
                                                        new List<Types> { Types.Normal, Types.Fairy }, 1.0, 12.0 ),
                "nosferapti" => new Pokemons( "Nosferapti", level, new Dictionary<string, int> { { "hp", 40 }, { "atk", 45 }, { "def", 35 }, { "atkspe", 30 }, { "defspe", 40 }, { "speed", 55 }, { "special", 30 } },
                                                        new List<Types> { Types.Poison, Types.Flying }, 0.5, 7.5 ),
                "nosferalto" => new Pokemons( "Nosferalto", level, new Dictionary<string, int> { { "hp", 75 }, { "atk", 80 }, { "def", 70 }, { "atkspe", 65 }, { "defspe", 75 }, { "speed", 90 }, { "special", 75 } },
                                                        new List<Types> { Types.Poison, Types.Flying }, 1.6, 55.0 ),
                "mystherbe" => new Pokemons( "Mystherbe", level, new Dictionary<string, int> { { "hp", 45 }, { "atk", 50 }, { "def", 55 }, { "atkspe", 75 }, { "defspe", 65 }, { "speed", 30 }, { "special", 75 } },
                                                        new List<Types> { Types.Grass, Types.Poison }, 0.5, 5.4 ),
                "ortide" => new Pokemons( "Ortide", level, new Dictionary<string, int> { { "hp", 60 }, { "atk", 65 }, { "def", 70 }, { "atkspe", 85 }, { "defspe", 75 }, { "speed", 40 }, { "special", 85 } },
                                                        new List<Types> { Types.Grass, Types.Poison }, 0.8, 8.6 ),
                "rafflesia" => new Pokemons( "Rafflesia", level, new Dictionary<string, int> { { "hp", 75 }, { "atk", 80 }, { "def", 85 }, { "atkspe", 110 }, { "defspe", 90 }, { "speed", 50 }, { "special", 110 } },
                                                        new List<Types> { Types.Grass, Types.Poison }, 1.2, 18.6 ),
                "paras" => new Pokemons( "Paras", level, new Dictionary<string, int> { { "hp", 35 }, { "atk", 70 }, { "def", 55 }, { "atkspe", 45 }, { "defspe", 55 }, { "speed", 25 }, { "special", 45 } },
                                                        new List<Types> { Types.Bug, Types.Grass }, 0.3, 5.4 ),
                "parasect" => new Pokemons( "Parasect", level, new Dictionary<string, int> { { "hp", 60 }, { "atk", 95 }, { "def", 80 }, { "atkspe", 60 }, { "defspe", 80 }, { "speed", 30 }, { "special", 60 } },
                                                        new List<Types> { Types.Bug, Types.Grass }, 1.0, 29.5 ),
                "mimitoss" => new Pokemons( "Mimitoss", level, new Dictionary<string, int> { { "hp", 60 }, { "atk", 55 }, { "def", 50 }, { "atkspe", 40 }, { "defspe", 55 }, { "speed", 45 }, { "special", 40 } },
                                                        new List<Types> { Types.Bug, Types.Poison }, 0.5, 5.5 ),
                "aeromite" => new Pokemons( "Aeromite", level, new Dictionary<string, int> { { "hp", 70 }, { "atk", 65 }, { "def", 60 }, { "atkspe", 90 }, { "defspe", 75 }, { "speed", 90 }, { "special", 90 } },
                                                        new List<Types> { Types.Bug, Types.Poison }, 1.0, 29.5 ),
                "taupiqueur" => new Pokemons( "Taupiqueur", level, new Dictionary<string, int> { { "hp", 10 }, { "atk", 55 }, { "def", 25 }, { "atkspe", 35 }, { "defspe", 45 }, { "speed", 95 }, { "special", 35 } },
                                                        new List<Types> { Types.Ground }, 0.2, 0.8 ),
                "triopikeur" => new Pokemons( "Triopikeur", level, new Dictionary<string, int> { { "hp", 35 }, { "atk", 80 }, { "def", 50 }, { "atkspe", 50 }, { "defspe", 70 }, { "speed", 120 }, { "special", 50 } },
                                                        new List<Types> { Types.Ground }, 0.7, 33.3 ),
                "miaouss" => new Pokemons( "Miaouss", level, new Dictionary<string, int> { { "hp", 40 }, { "atk", 45 }, { "def", 35 }, { "atkspe", 40 }, { "defspe", 40 }, { "speed", 90 }, { "special", 40 } },
                                                        new List<Types> { Types.Normal }, 0.4, 4.2 ),
                "persian" => new Pokemons( "Persian", level, new Dictionary<string, int> { { "hp", 65 }, { "atk", 70 }, { "def", 60 }, { "atkspe", 65 }, { "defspe", 65 }, { "speed", 115 }, { "special", 65 } },
                                                        new List<Types> { Types.Normal }, 1.0, 32.0 ),
                "psykokwak" => new Pokemons( "Psykokwak", level, new Dictionary<string, int> { { "hp", 50 }, { "atk", 52 }, { "def", 48 }, { "atkspe", 65 }, { "defspe", 50 }, { "speed", 55 }, { "special", 50 } },
                                                        new List<Types> { Types.Water }, 0.8, 19.6 ),
                "akwakwak" => new Pokemons( "Akwakwak", level, new Dictionary<string, int> { { "hp", 80 }, { "atk", 82 }, { "def", 78 }, { "atkspe", 95 }, { "defspe", 80 }, { "speed", 85 }, { "special", 85 } },
                                                        new List<Types> { Types.Water }, 1.7, 76.6 ),
                "ferosinge" => new Pokemons( "Ferosinge", level, new Dictionary<string, int> { { "hp", 40 }, { "atk", 80 }, { "def", 35 }, { "atkspe", 35 }, { "defspe", 45 }, { "speed", 70 }, { "special", 35 } },
                                                        new List<Types> { Types.Fighting }, 0.5, 28.0 ),
                "colossinge" => new Pokemons( "Colossinge", level, new Dictionary<string, int> { { "hp", 65 }, { "atk", 105 }, { "def", 60 }, { "atkspe", 60 }, { "defspe", 70 }, { "speed", 95 }, { "special", 60 } },
                                                        new List<Types> { Types.Fighting }, 1.0, 32.0 ),
                "caninos" => new Pokemons( "Caninos", level, new Dictionary<string, int> { { "hp", 55 }, { "atk", 70 }, { "def", 45 }, { "atkspe", 70 }, { "defspe", 50 }, { "speed", 60 }, { "special", 70 } },
                                                        new List<Types> { Types.Fire }, 0.7, 19.0 ),
                "arcanin" => new Pokemons( "Arcanin", level, new Dictionary<string, int> { { "hp", 90 }, { "atk", 110 }, { "def", 80 }, { "atkspe", 100 }, { "defspe", 80 }, { "speed", 95 }, { "special", 100 } },
                                                        new List<Types> { Types.Fire }, 1.9, 155.0 ),
                "ptitard" => new Pokemons( "Ptitard", level, new Dictionary<string, int> { { "hp", 40 }, { "atk", 50 }, { "def", 40 }, { "atkspe", 40 }, { "defspe", 40 }, { "speed", 90 }, { "special", 40 } },
                                                        new List<Types> { Types.Water, Types.Flying }, 0.3, 2.0 ),
                "tetarte" => new Pokemons( "Tetarte", level, new Dictionary<string, int> { { "hp", 65 }, { "atk", 65 }, { "def", 65 }, { "atkspe", 50 }, { "defspe", 50 }, { "speed", 90 }, { "special", 50 } },
                                                        new List<Types> { Types.Water, Types.Fighting }, 1.0, 20.0 ),
                "tartard" => new Pokemons( "Tartard", level, new Dictionary<string, int> { { "hp", 90 }, { "atk", 95 }, { "def", 95 }, { "atkspe", 70 }, { "defspe", 90 }, { "speed", 70 }, { "special", 70 } },
                                                        new List<Types> { Types.Water, Types.Fighting }, 1.3, 54.0 ),
                "abra" => new Pokemons( "Abra", level, new Dictionary<string, int> { { "hp", 25 }, { "atk", 20 }, { "def", 15 }, { "atkspe", 105 }, { "defspe", 55 }, { "speed", 90 }, { "special", 105 } },
                                                        new List<Types> { Types.Psychic }, 0.9, 19.5 ),
                "kadabra" => new Pokemons( "Kadabra", level, new Dictionary<string, int> { { "hp", 40 }, { "atk", 35 }, { "def", 30 }, { "atkspe", 120 }, { "defspe", 70 }, { "speed", 105 }, { "special", 120 } },
                                                        new List<Types> { Types.Psychic }, 1.3, 56.5 ),
                "alakazam" => new Pokemons( "Alakazam", level, new Dictionary<string, int> { { "hp", 55 }, { "atk", 50 }, { "def", 45 }, { "atkspe", 135 }, { "defspe", 85 }, { "speed", 120 }, { "special", 135 } },
                                                        new List<Types> { Types.Psychic }, 1.5, 48.0 ),
                "machoc" => new Pokemons( "Machoc", level, new Dictionary<string, int> { { "hp", 70 }, { "atk", 80 }, { "def", 50 }, { "atkspe", 35 }, { "defspe", 35 }, { "speed", 35 }, { "special", 35 } },
                                                        new List<Types> { Types.Fighting }, 0.8, 19.5 ),
                "machopeur" => new Pokemons( "Machopeur", level, new Dictionary<string, int> { { "hp", 80 }, { "atk", 100 }, { "def", 70 }, { "atkspe", 50 }, { "defspe", 60 }, { "speed", 45 }, { "special", 50 } },
                                                        new List<Types> { Types.Fighting }, 1.5, 70.5 ),
                "mackogneur" => new Pokemons( "Mackogneur", level, new Dictionary<string, int> { { "hp", 90 }, { "atk", 130 }, { "def", 80 }, { "atkspe", 65 }, { "defspe", 85 }, { "speed", 55 }, { "special", 65 } },
                                                        new List<Types> { Types.Fighting }, 1.6, 130.0 ),
                "chetiflor" => new Pokemons( "Chetiflor", level, new Dictionary<string, int> { { "hp", 50 }, { "atk", 75 }, { "def", 35 }, { "atkspe", 70 }, { "defspe", 30 }, { "speed", 40 }, { "special", 70 } },
                                                        new List<Types> { Types.Grass, Types.Poison }, 0.4, 5.4 ),
                "boustiflor" => new Pokemons( "Boustiflor", level, new Dictionary<string, int> { { "hp", 65 }, { "atk", 90 }, { "def", 50 }, { "atkspe", 85 }, { "defspe", 45 }, { "speed", 55 }, { "special", 85 } },
                                                        new List<Types> { Types.Grass, Types.Poison }, 1.0, 8.6 ),
                "empiflor" => new Pokemons( "Empiflor", level, new Dictionary<string, int> { { "hp", 80 }, { "atk", 105 }, { "def", 65 }, { "atkspe", 100 }, { "defspe", 70 }, { "speed", 70 }, { "special", 100 } },
                                                        new List<Types> { Types.Grass, Types.Poison }, 1.7, 18.6 ),
                "tentacool" => new Pokemons( "Tentacool", level, new Dictionary<string, int> { { "hp", 40 }, { "atk", 40 }, { "def", 35 }, { "atkspe", 50 }, { "defspe", 100 }, { "speed", 70 }, { "special", 50 } },
                                                        new List<Types> { Types.Water, Types.Poison }, 0.9, 45.5 ),
                "tentacruel" => new Pokemons( "Tentacruel", level, new Dictionary<string, int> { { "hp", 80 }, { "atk", 70 }, { "def", 65 }, { "atkspe", 80 }, { "defspe", 120 }, { "speed", 100 }, { "special", 80 } },
                                                        new List<Types> { Types.Water, Types.Poison }, 1.6, 55.0 ),
                "racaillou" => new Pokemons( "Racaillou", level, new Dictionary<string, int> { { "hp", 40 }, { "atk", 80 }, { "def", 100 }, { "atkspe", 30 }, { "defspe", 30 }, { "speed", 20 }, { "special", 30 } },
                                                        new List<Types> { Types.Rock, Types.Ground }, 0.4, 20.0 ),
                "gravalanch" => new Pokemons( "Gravalanch", level, new Dictionary<string, int> { { "hp", 55 }, { "atk", 95 }, { "def", 115 }, { "atkspe", 45 }, { "defspe", 45 }, { "speed", 35 }, { "special", 45 } },
                                                        new List<Types> { Types.Rock, Types.Ground }, 1.0, 105.0 ),
                "grolem" => new Pokemons( "Grolem", level, new Dictionary<string, int> { { "hp", 80 }, { "atk", 120 }, { "def", 130 }, { "atkspe", 55 }, { "defspe", 65 }, { "speed", 45 }, { "special", 55 } },
                                                        new List<Types> { Types.Rock, Types.Ground }, 1.4, 300.0 ),
                "ponyta" => new Pokemons( "Ponyta", level, new Dictionary<string, int> { { "hp", 50 }, { "atk", 85 }, { "def", 55 }, { "atkspe", 65 }, { "defspe", 65 }, { "speed", 90 }, { "special", 65 } },
                                                        new List<Types> { Types.Fire }, 1.0, 30.0 ),
                "galopa" => new Pokemons( "Galopa", level, new Dictionary<string, int> { { "hp", 65 }, { "atk", 100 }, { "def", 70 }, { "atkspe", 80 }, { "defspe", 80 }, { "speed", 105 }, { "special", 80 } },
                                                        new List<Types> { Types.Fire }, 1.7, 95.0 ),
                "ramoloss" => new Pokemons( "Ramoloss", level, new Dictionary<string, int> { { "hp", 90 }, { "atk", 65 }, { "def", 65 }, { "atkspe", 40 }, { "defspe", 40 }, { "speed", 15 }, { "special", 40 } },
                                                        new List<Types> { Types.Water, Types.Psychic }, 1.2, 78.5 ),
                "flagadoss" => new Pokemons( "Flagadoss", level, new Dictionary<string, int> { { "hp", 95 }, { "atk", 75 }, { "def", 110 }, { "atkspe", 100 }, { "defspe", 80 }, { "speed", 30 }, { "special", 100 } },
                                                        new List<Types> { Types.Water, Types.Psychic }, 1.6, 85.6 ),
                "magneti" => new Pokemons( "Magneti", level, new Dictionary<string, int> { { "hp", 25 }, { "atk", 35 }, { "def", 70 }, { "atkspe", 95 }, { "defspe", 55 }, { "speed", 45 }, { "special", 95 } },
                                                        new List<Types> { Types.Electric, Types.Steel }, 0.3, 6.0 ),
                "magneton" => new Pokemons( "Magneton", level, new Dictionary<string, int> { { "hp", 50 }, { "atk", 60 }, { "def", 95 }, { "atkspe", 120 }, { "defspe", 70 }, { "speed", 70 }, { "special", 120 } },
                                                        new List<Types> { Types.Electric, Types.Steel }, 1.0, 60.0 ),
                "canarticho" => new Pokemons( "Canarticho", level, new Dictionary<string, int> { { "hp", 52 }, { "atk", 90 }, { "def", 55 }, { "atkspe", 58 }, { "defspe", 62 }, { "speed", 55 }, { "special", 58 } },
                                                        new List<Types> { Types.Normal }, 0.8, 15.0 ),
                "doduo" => new Pokemons( "Doduo", level, new Dictionary<string, int> { { "hp", 35 }, { "atk", 85 }, { "def", 45 }, { "atkspe", 35 }, { "defspe", 35 }, { "speed", 75 }, { "special", 35 } },
                                                        new List<Types> { Types.Normal, Types.Flying }, 1.4, 39.2 ),
                "dodrio" => new Pokemons( "Dodrio", level, new Dictionary<string, int> { { "hp", 60 }, { "atk", 110 }, { "def", 70 }, { "atkspe", 60 }, { "defspe", 60 }, { "speed", 100 }, { "special", 60 } },
                                                        new List<Types> { Types.Normal, Types.Flying }, 1.8, 85.2 ),
                "otaria" => new Pokemons( "Otaria", level, new Dictionary<string, int> { { "hp", 65 }, { "atk", 45 }, { "def", 55 }, { "atkspe", 45 }, { "defspe", 70 }, { "speed", 45 }, { "special", 45 } },
                                                        new List<Types> { Types.Water, Types.Ice }, 1.1, 90.0 ),
                "lamantine" => new Pokemons( "Lamantine", level, new Dictionary<string, int> { { "hp", 90 }, { "atk", 70 }, { "def", 80 }, { "atkspe", 70 }, { "defspe", 95 }, { "speed", 70 }, { "special", 70 } },
                                                        new List<Types> { Types.Water, Types.Ice }, 1.7, 120.0 ),
                "tadmorv" => new Pokemons( "Tadmorv", level, new Dictionary<string, int> { { "hp", 80 }, { "atk", 80 }, { "def", 50 }, { "atkspe", 40 }, { "defspe", 50 }, { "speed", 25 }, { "special", 40 } },
                                                        new List<Types> { Types.Poison }, 1.0, 30.0 ),
                "grotadmorv" => new Pokemons( "Grotadmorv", level, new Dictionary<string, int> { { "hp", 105 }, { "atk", 105 }, { "def", 75 }, { "atkspe", 65 }, { "defspe", 100 }, { "speed", 50 }, { "special", 65 } },
                                                        new List<Types> { Types.Poison }, 1.4, 30.0 ),
                "kokiyas" => new Pokemons( "Kokiyas", level, new Dictionary<string, int> { { "hp", 30 }, { "atk", 65 }, { "def", 100 }, { "atkspe", 45 }, { "defspe", 25 }, { "speed", 40 }, { "special", 45 } },
                                                        new List<Types> { Types.Water }, 0.4, 4.2 ),
                "crustabri" => new Pokemons( "Crustabri", level, new Dictionary<string, int> { { "hp", 50 }, { "atk", 95 }, { "def", 180 }, { "atkspe", 85 }, { "defspe", 45 }, { "speed", 70 }, { "special", 85 } },
                                                        new List<Types> { Types.Water, Types.Ice }, 1.6, 132.5 ),
                "fantominus" => new Pokemons( "Fantominus", level, new Dictionary<string, int> { { "hp", 30 }, { "atk", 35 }, { "def", 30 }, { "atkspe", 100 }, { "defspe", 35 }, { "speed", 80 }, { "special", 100 } },
                                                        new List<Types> { Types.Ghost, Types.Poison }, 0.8, 0.1 ),
                "spectrum" => new Pokemons( "Spectrum", level, new Dictionary<string, int> { { "hp", 45 }, { "atk", 50 }, { "def", 45 }, { "atkspe", 115 }, { "defspe", 55 }, { "speed", 95 }, { "special", 115 } },
                                                        new List<Types> { Types.Ghost, Types.Poison }, 1.6, 0.1 ),
                "ectoplasma" => new Pokemons( "Ectoplasma", level, new Dictionary<string, int> { { "hp", 60 }, { "atk", 65 }, { "def", 60 }, { "atkspe", 130 }, { "defspe", 75 }, { "speed", 110 }, { "special", 130 } },
                                                        new List<Types> { Types.Ghost, Types.Poison }, 1.5, 40.5 ),
                "onix" => new Pokemons( "Onix", level, new Dictionary<string, int> { { "hp", 35 }, { "atk", 45 }, { "def", 160 }, { "atkspe", 30 }, { "defspe", 45 }, { "speed", 70 }, { "special", 30 } },
                                                        new List<Types> { Types.Rock, Types.Ground }, 8.8, 210.0 ),
                "soporifik" => new Pokemons( "Soporifik", level, new Dictionary<string, int> { { "hp", 60 }, { "atk", 48 }, { "def", 45 }, { "atkspe", 43 }, { "defspe", 90 }, { "speed", 42 }, { "special", 43 } },
                                                        new List<Types> { Types.Psychic }, 1.1, 32.4 ),
                "hypnomade" => new Pokemons( "Hypnomade", level, new Dictionary<string, int> { { "hp", 85 }, { "atk", 73 }, { "def", 70 }, { "atkspe", 73 }, { "defspe", 115 }, { "speed", 67 }, { "special", 73 } },
                                                        new List<Types> { Types.Psychic }, 1.6, 75.6 ),
                "krabby" => new Pokemons( "Krabby", level, new Dictionary<string, int> { { "hp", 30 }, { "atk", 105 }, { "def", 90 }, { "atkspe", 25 }, { "defspe", 25 }, { "speed", 50 }, { "special", 25 } },
                                                        new List<Types> { Types.Water }, 0.4, 6.5 ),
                "krabboss" => new Pokemons( "Krabboss", level, new Dictionary<string, int> { { "hp", 55 }, { "atk", 130 }, { "def", 115 }, { "atkspe", 50 }, { "defspe", 50 }, { "speed", 75 }, { "special", 50 } },
                                                        new List<Types> { Types.Water }, 1.3, 60.0 ),
                "voltorbe" => new Pokemons( "Voltorbe", level, new Dictionary<string, int> { { "hp", 40 }, { "atk", 30 }, { "def", 50 }, { "atkspe", 55 }, { "defspe", 55 }, { "speed", 100 }, { "special", 55 } },
                                                        new List<Types> { Types.Electric }, 0.5, 10.4 ),
                "electrode" => new Pokemons( "Electrode", level, new Dictionary<string, int> { { "hp", 60 }, { "atk", 50 }, { "def", 70 }, { "atkspe", 80 }, { "defspe", 80 }, { "speed", 140 }, { "special", 80 } },
                                                        new List<Types> { Types.Electric }, 1.2, 66.6 ),
                "noeunoeuf" => new Pokemons( "Noeunoeuf", level, new Dictionary<string, int> { { "hp", 60 }, { "atk", 40 }, { "def", 80 }, { "atkspe", 60 }, { "defspe", 45 }, { "speed", 40 }, { "special", 60 } },
                                                        new List<Types> { Types.Grass, Types.Psychic }, 0.4, 2.5 ),
                "noadkoko" => new Pokemons( "Noadkoko", level, new Dictionary<string, int> { { "hp", 95 }, { "atk", 95 }, { "def", 85 }, { "atkspe", 125 }, { "defspe", 75 }, { "speed", 55 }, { "special", 125 } },
                                                        new List<Types> { Types.Grass, Types.Psychic }, 1.7, 120.0 ),
                "osselait" => new Pokemons( "Osselait", level, new Dictionary<string, int> { { "hp", 50 }, { "atk", 50 }, { "def", 95 }, { "atkspe", 40 }, { "defspe", 50 }, { "speed", 35 }, { "special", 40 } },
                                                        new List<Types> { Types.Ground }, 0.4, 6.5 ),
                "ossatueur" => new Pokemons( "Ossatueur", level, new Dictionary<string, int> { { "hp", 60 }, { "atk", 80 }, { "def", 110 }, { "atkspe", 50 }, { "defspe", 80 }, { "speed", 45 }, { "special", 50 } },
                                                        new List<Types> { Types.Ground }, 1.0, 45.0 ),
                "kicklee" => new Pokemons( "Kicklee", level, new Dictionary<string, int> { { "hp", 50 }, { "atk", 120 }, { "def", 53 }, { "atkspe", 35 }, { "defspe", 110 }, { "speed", 87 }, { "special", 35 } },
                                                        new List<Types> { Types.Fighting }, 1.5, 49.8 ),
                "tygnon" => new Pokemons( "Tygnon", level, new Dictionary<string, int> { { "hp", 50 }, { "atk", 105 }, { "def", 79 }, { "atkspe", 35 }, { "defspe", 110 }, { "speed", 76 }, { "special", 35 } },
                                                        new List<Types> { Types.Fighting }, 1.4, 50.2 ),
                "excelangue" => new Pokemons( "Excelangue", level, new Dictionary<string, int> { { "hp", 90 }, { "atk", 55 }, { "def", 75 }, { "atkspe", 60 }, { "defspe", 75 }, { "speed", 30 }, { "special", 60 } },
                                                        new List<Types> { Types.Normal }, 1.2, 65.5 ),
                "smogo" => new Pokemons( "Smogo", level, new Dictionary<string, int> { { "hp", 40 }, { "atk", 65 }, { "def", 95 }, { "atkspe", 60 }, { "defspe", 45 }, { "speed", 35 }, { "special", 60 } },
                                                        new List<Types> { Types.Poison }, 0.6, 1.0 ),
                "smogogo" => new Pokemons( "Smogogo", level, new Dictionary<string, int> { { "hp", 65 }, { "atk", 90 }, { "def", 120 }, { "atkspe", 85 }, { "defspe", 70 }, { "speed", 60 }, { "special", 85 } },
                                                        new List<Types> { Types.Poison }, 1.2, 9.5 ),
                "rhinocorne" => new Pokemons( "Rhinocorne", level, new Dictionary<string, int> { { "hp", 80 }, { "atk", 85 }, { "def", 95 }, { "atkspe", 30 }, { "defspe", 30 }, { "speed", 25 }, { "special", 30 } },
                                                        new List<Types> { Types.Ground, Types.Rock }, 1.0, 115.0 ),
                "rhinoferos" => new Pokemons( "Rhinoferos", level, new Dictionary<string, int> { { "hp", 105 }, { "atk", 130 }, { "def", 120 }, { "atkspe", 45 }, { "defspe", 45 }, { "speed", 40 }, { "special", 45 } },
                                                        new List<Types> { Types.Ground, Types.Rock }, 1.9, 120.0 ),
                "leveinard" => new Pokemons( "Leveinard", level, new Dictionary<string, int> { { "hp", 250 }, { "atk", 5 }, { "def", 5 }, { "atkspe", 35 }, { "defspe", 105 }, { "speed", 50 }, { "special", 35 } },
                                                        new List<Types> { Types.Normal }, 1.1, 34.6 ),
                "saquedeneu" => new Pokemons( "Saquedeneu", level, new Dictionary<string, int> { { "hp", 65 }, { "atk", 55 }, { "def", 115 }, { "atkspe", 100 }, { "defspe", 40 }, { "speed", 60 }, { "special", 100 } },
                                                        new List<Types> { Types.Grass }, 1.2, 35.0 ),
                "kangourex" => new Pokemons( "Kangourex", level, new Dictionary<string, int> { { "hp", 105 }, { "atk", 95 }, { "def", 80 }, { "atkspe", 40 }, { "defspe", 80 }, { "speed", 90 }, { "special", 40 } },
                                                        new List<Types> { Types.Normal }, 2.2, 80.0 ),
                "hypocean" => new Pokemons( "Hypocean", level, new Dictionary<string, int> { { "hp", 30 }, { "atk", 40 }, { "def", 70 }, { "atkspe", 70 }, { "defspe", 25 }, { "speed", 60 }, { "special", 70 } },
                                                        new List<Types> { Types.Water }, 0.6, 12.0 ),
                "hypotrempe" => new Pokemons( "Hypotrempe", level, new Dictionary<string, int> { { "hp", 85 }, { "atk", 80 }, { "def", 80 }, { "atkspe", 110 }, { "defspe", 90 }, { "speed", 60 }, { "special", 110 } },
                                                        new List<Types> { Types.Water, Types.Dragon }, 1.7, 235.0 ),
                "poissirene" => new Pokemons( "Poissirene", level, new Dictionary<string, int> { { "hp", 45 }, { "atk", 67 }, { "def", 60 }, { "atkspe", 35 }, { "defspe", 50 }, { "speed", 63 }, { "special", 50 } },
                                                        new List<Types> { Types.Water }, 0.6, 15.0 ),
                "poissoroy" => new Pokemons( "Poissoroy", level, new Dictionary<string, int> { { "hp", 80 }, { "atk", 92 }, { "def", 65 }, { "atkspe", 65 }, { "defspe", 80 }, { "speed", 68 }, { "special", 80 } },
                                                        new List<Types> { Types.Water }, 1.3, 39.0 ),
                "stari" => new Pokemons( "Stari", level, new Dictionary<string, int> { { "hp", 30 }, { "atk", 45 }, { "def", 55 }, { "atkspe", 70 }, { "defspe", 55 }, { "speed", 85 }, { "special", 70 } },
                                                        new List<Types> { Types.Water }, 0.8, 34.5 ),
                "staross" => new Pokemons( "Staross", level, new Dictionary<string, int> { { "hp", 60 }, { "atk", 75 }, { "def", 85 }, { "atkspe", 100 }, { "defspe", 85 }, { "speed", 115 }, { "special", 100 } },
                                                        new List<Types> { Types.Water, Types.Psychic }, 1.1, 80.0 ),
                "mmime" => new Pokemons( "MMime", level, new Dictionary<string, int> { { "hp", 40 }, { "atk", 45 }, { "def", 65 }, { "atkspe", 100 }, { "defspe", 120 }, { "speed", 90 }, { "special", 100 } },
                                                        new List<Types> { Types.Psychic, Types.Fairy }, 1.3, 54.5 ),
                "insecateur" => new Pokemons( "Insecateur", level, new Dictionary<string, int> { { "hp", 70 }, { "atk", 110 }, { "def", 80 }, { "atkspe", 55 }, { "defspe", 80 }, { "speed", 105 }, { "special", 55 } },
                                                        new List<Types> { Types.Bug, Types.Flying }, 1.1, 59.0 ),
                "lippoutou" => new Pokemons( "Lippoutou", level, new Dictionary<string, int> { { "hp", 90 }, { "atk", 50 }, { "def", 75 }, { "atkspe", 95 }, { "defspe", 135 }, { "speed", 55 }, { "special", 95 } },
                                                        new List<Types> { Types.Ice, Types.Psychic }, 1.4, 40.6 ),
                "elektek" => new Pokemons( "Elektek", level, new Dictionary<string, int> { { "hp", 65 }, { "atk", 83 }, { "def", 57 }, { "atkspe", 95 }, { "defspe", 85 }, { "speed", 105 }, { "special", 95 } },
                                                        new List<Types> { Types.Electric }, 1.1, 30.0 ),
                "magmar" => new Pokemons( "Magmar", level, new Dictionary<string, int> { { "hp", 65 }, { "atk", 95 }, { "def", 57 }, { "atkspe", 100 }, { "defspe", 85 }, { "speed", 93 }, { "special", 100 } },
                                                        new List<Types> { Types.Fire }, 1.3, 44.5 ),
                "scarabrute" => new Pokemons( "Scarabrute", level, new Dictionary<string, int> { { "hp", 75 }, { "atk", 125 }, { "def", 100 }, { "atkspe", 55 }, { "defspe", 70 }, { "speed", 85 }, { "special", 55 } },
                                                        new List<Types> { Types.Bug }, 1.5, 55.0 ),
                "tauros" => new Pokemons( "Tauros", level, new Dictionary<string, int> { { "hp", 75 }, { "atk", 100 }, { "def", 95 }, { "atkspe", 40 }, { "defspe", 70 }, { "speed", 110 }, { "special", 40 } },
                                                        new List<Types> { Types.Normal }, 1.4, 88.4 ),
                "magicarpe" => new Pokemons( "Magicarpe", level, new Dictionary<string, int> { { "hp", 20 }, { "atk", 10 }, { "def", 55 }, { "atkspe", 15 }, { "defspe", 20 }, { "speed", 80 }, { "special", 20 } },
                                                        new List<Types> { Types.Water }, 0.9, 10.0 ),
                "leviator" => new Pokemons( "Leviator", level, new Dictionary<string, int> { { "hp", 95 }, { "atk", 125 }, { "def", 79 }, { "atkspe", 60 }, { "defspe", 100 }, { "speed", 81 }, { "special", 60 } },
                                                        new List<Types> { Types.Water, Types.Flying }, 2.5, 235.0 ),
                "lokhlass" => new Pokemons( "Lokhlass", level, new Dictionary<string, int> { { "hp", 130 }, { "atk", 85 }, { "def", 80 }, { "atkspe", 85 }, { "defspe", 95 }, { "speed", 60 }, { "special", 85 } },
                                                        new List<Types> { Types.Water, Types.Ice }, 2.5, 220.0 ),
                "metamorph" => new Pokemons( "Metamorph", level, new Dictionary<string, int> { { "hp", 48 }, { "atk", 48 }, { "def", 48 }, { "atkspe", 48 }, { "defspe", 48 }, { "speed", 48 }, { "special", 48 } },
                                                        new List<Types> { Types.Normal }, 0.3, 4.0 ),
                "evoli" => new Pokemons( "Evoli", level, new Dictionary<string, int> { { "hp", 55 }, { "atk", 55 }, { "def", 50 }, { "atkspe", 45 }, { "defspe", 65 }, { "speed", 55 }, { "special", 45 } },
                                                        new List<Types> { Types.Normal }, 0.3, 6.5 ),
                "aquali" => new Pokemons( "Aquali", level, new Dictionary<string, int> { { "hp", 130 }, { "atk", 65 }, { "def", 60 }, { "atkspe", 110 }, { "defspe", 95 }, { "speed", 65 }, { "special", 110 } },
                                                        new List<Types> { Types.Water }, 1.0, 29.0 ),
                "voltali" => new Pokemons( "Voltali", level, new Dictionary<string, int> { { "hp", 65 }, { "atk", 65 }, { "def", 60 }, { "atkspe", 110 }, { "defspe", 95 }, { "speed", 130 }, { "special", 110 } },
                                                        new List<Types> { Types.Electric }, 0.8, 24.5 ),
                "pyroli" => new Pokemons( "Pyroli", level, new Dictionary<string, int> { { "hp", 65 }, { "atk", 130 }, { "def", 60 }, { "atkspe", 95 }, { "defspe", 110 }, { "speed", 65 }, { "special", 95 } },
                                                        new List<Types> { Types.Fire }, 0.9, 25.0 ),
                "porygon" => new Pokemons( "Porygon", level, new Dictionary<string, int> { { "hp", 65 }, { "atk", 60 }, { "def", 70 }, { "atkspe", 85 }, { "defspe", 75 }, { "speed", 40 }, { "special", 85 } },
                                                        new List<Types> { Types.Normal }, 0.8, 36.5 ),
                "amonita" => new Pokemons( "Amonita", level, new Dictionary<string, int> { { "hp", 35 }, { "atk", 40 }, { "def", 100 }, { "atkspe", 90 }, { "defspe", 55 }, { "speed", 35 }, { "special", 90 } },
                                                        new List<Types> { Types.Rock, Types.Water }, 0.4, 7.5 ),
                "amonistar" => new Pokemons( "Amonistar", level, new Dictionary<string, int> { { "hp", 70 }, { "atk", 60 }, { "def", 125 }, { "atkspe", 115 }, { "defspe", 70 }, { "speed", 55 }, { "special", 115 } },
                                                        new List<Types> { Types.Rock, Types.Water }, 1.0, 35.0 ),
                "kabuto" => new Pokemons( "Kabuto", level, new Dictionary<string, int> { { "hp", 30 }, { "atk", 80 }, { "def", 90 }, { "atkspe", 55 }, { "defspe", 45 }, { "speed", 55 }, { "special", 55 } },
                                                        new List<Types> { Types.Rock, Types.Water }, 0.5, 11.5 ),
                "kabutops" => new Pokemons( "Kabutops", level, new Dictionary<string, int> { { "hp", 60 }, { "atk", 115 }, { "def", 105 }, { "atkspe", 65 }, { "defspe", 70 }, { "speed", 80 }, { "special", 65 } },
                                                        new List<Types> { Types.Rock, Types.Water }, 1.3, 40.5 ),
                "ptera" => new Pokemons( "Ptera", level, new Dictionary<string, int> { { "hp", 80 }, { "atk", 105 }, { "def", 65 }, { "atkspe", 60 }, { "defspe", 75 }, { "speed", 130 }, { "special", 60 } },
                                                        new List<Types> { Types.Rock, Types.Flying }, 1.8, 59.0 ),
                "ronflex" => new Pokemons( "Ronflex", level, new Dictionary<string, int> { { "hp", 160 }, { "atk", 110 }, { "def", 65 }, { "atkspe", 65 }, { "defspe", 110 }, { "speed", 30 }, { "special", 65 } },
                                                        new List<Types> { Types.Normal }, 2.1, 460.0 ),
                "artikodin" => new Pokemons( "Artikodin", level, new Dictionary<string, int> { { "hp", 90 }, { "atk", 85 }, { "def", 100 }, { "atkspe", 95 }, { "defspe", 125 }, { "speed", 85 }, { "special", 125 } },
                                                        new List<Types> { Types.Ice, Types.Flying }, 1.7, 55.4 ),
                "electhor" => new Pokemons( "Electhor", level, new Dictionary<string, int> { { "hp", 90 }, { "atk", 90 }, { "def", 85 }, { "atkspe", 125 }, { "defspe", 90 }, { "speed", 100 }, { "special", 125 } },
                                                        new List<Types> { Types.Electric, Types.Flying }, 1.6, 52.6 ),
                "sulfura" => new Pokemons( "Sulfura", level, new Dictionary<string, int> { { "hp", 90 }, { "atk", 100 }, { "def", 90 }, { "atkspe", 125 }, { "defspe", 85 }, { "speed", 90 }, { "special", 125 } },
                                                        new List<Types> { Types.Fire, Types.Flying }, 2.0, 60.0 ),
                "minidraco" => new Pokemons( "Minidraco", level, new Dictionary<string, int> { { "hp", 41 }, { "atk", 64 }, { "def", 45 }, { "atkspe", 50 }, { "defspe", 50 }, { "speed", 50 }, { "special", 50 } },
                                                        new List<Types> { Types.Dragon }, 1.8, 3.3 ),
                "draco" => new Pokemons( "Draco", level, new Dictionary<string, int> { { "hp", 61 }, { "atk", 84 }, { "def", 65 }, { "atkspe", 70 }, { "defspe", 70 }, { "speed", 70 }, { "special", 70 } },
                                                        new List<Types> { Types.Dragon }, 4.0, 16.5 ),
                "dracolosse" => new Pokemons( "Dracolosse", level, new Dictionary<string, int> { { "hp", 91 }, { "atk", 134 }, { "def", 95 }, { "atkspe", 100 }, { "defspe", 100 }, { "speed", 80 }, { "special", 100 } },
                                                        new List<Types> { Types.Dragon, Types.Flying }, 2.2, 210.0 ),
                "mewtwo" => new Pokemons( "Mewtwo", level, new Dictionary<string, int> { { "hp", 106 }, { "atk", 110 }, { "def", 90 }, { "atkspe", 154 }, { "defspe", 90 }, { "speed", 130 }, { "special", 154 } },
                                                        new List<Types> { Types.Psychic }, 2.0, 122.0 ),
                "mew" => new Pokemons( "Mew", level, new Dictionary<string, int> { { "hp", 100 }, { "atk", 100 }, { "def", 100 }, { "atkspe", 100 }, { "defspe", 100 }, { "speed", 100 }, { "special", 100 } },
                                                        new List<Types> { Types.Psychic }, 0.4, 4.0 ),
                "mamadot" => new Pokemons( "Mamadot", level, new Dictionary<string, int> { { "hp", 500 }, { "atk", 20 }, { "def", 5000 }, { "atkspe", 20 }, { "defspe", 5000 }, { "speed", 999 }, { "special", 999 } },
                                                        new List<Types> { Types.Normal }, 1.82, 63.0 ),
                _ => throw new ArgumentException( $"Nom de Pokemon invalide. {name}" ),
            };
        }
    }
}
